By default data types in python: - "String", "Integer", "Float", "Boolean"

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one charecter

i - integer

b - boolean

u - unsigned integer


f - float

c - complex float

m - timedelta

M - Datetime

O - Object

S - String

U - unicode string

V - Fixed chunk of memoryfor other type(void)

# Checking the data type of an array

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [4]:
z = np.array(["animals","cat","bat"])
print(z.dtype)

<U7


# Creating Arrays with a defined data types

In [5]:
arr = np.array([1,2,3,4,5], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


# Create an array with defined data type 4 Bytes intger:

In [8]:
arr = np.array([1,2,3,4,5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


# NumPy Array Shape

### The shape of an array is the number of elements in each dimension.

# Print the shape of a 2-D array :

In [9]:
arr = np.array([[1,3,5],[2,4,6]])
print(arr.shape)

(2, 3)


In [11]:
arr = np.array([[1,3,5,7],[2,4,6,8]])
print(arr.shape)

(2, 4)


In [12]:
arr = np.array([2,4,6,8])
print(arr.shape)

(4,)


In [13]:
z = np.array([[[1,3,5],[2,3,4]],[[4,5,6],[7,8,9]]])
print(z.shape)


(2, 2, 3)


### Creat e an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that las dimension has value

In [14]:
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('Shape of array:', arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array: (1, 1, 1, 1, 4)


# Joining NumPy arrays

In [16]:
import numpy as np
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])

z = np.concatenate((ar1, ar2))

print(z)

[1 2 3 4 5 6]


# Join two 2_d arrays along rows(axis=1): Rows

In [22]:
import numpy as np
ar1 = np.array([[1,2,3],[1,3,5]])
ar2 = np.array([[4,5,6],[7,8,9]])
z = np.concatenate((ar1,ar2), axis=1)
print(z)

[[1 2 3 4 5 6]
 [1 3 5 7 8 9]]


In [23]:
import numpy as np
ar1 = np.array([[1,2,3],[1,3,5]])
ar2 = np.array([[4,5,6],[7,8,9]])
z = np.concatenate((ar1,ar2), axis=2)
print(z)

AxisError: axis 2 is out of bounds for array of dimension 2

# Join Two 2-D arrays along rows(axis=1): Column

In [24]:
import numpy as np
ar1 = np.array([[1,2,3],[1,3,5]])
ar2 = np.array([[4,5,6],[7,8,9]])
z = np.concatenate((ar1,ar2), axis=0)
print(z)

[[1 2 3]
 [1 3 5]
 [4 5 6]
 [7 8 9]]


# Splitting Numpy array

# Splitting is reverse operation of joining.

Joining merges multiple arrays ito one and splitting breaks one array into multiple

# Split the array in 3 parts:

In [25]:
arr = np.array([1,2,3,4,5,6])

z = np.array_split(arr,3)
print(z)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [26]:
arr = np.array([1,2,3,4,5,6])

z = np.array_split(arr,2)
print(z)

[array([1, 2, 3]), array([4, 5, 6])]


In [27]:
arr = np.array([1,2,3,4,5,6])

z = np.array_split(arr,4)
print(z)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## ravel & flatten - Converts multidimensional array into 1 d array

In [36]:
import numpy as np
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(m)
print("dimension is", m.ndim)

print()

n = m.ravel()
print(n)
print("Now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3

[1 2 3 4 5 6 7 8 9]
Now the new dimension is 1


### example 2

In [37]:
c  =np.array([[[1,2,3],[78,89,99],[45,56,23]]])
print(c)

print("Sot he dimension is", c.ndim)
print()
d = c.ravel()
print(d)

print("The dimension is", d.ndim)

[[[ 1  2  3]
  [78 89 99]
  [45 56 23]]]
Sot he dimension is 3

[ 1  2  3 78 89 99 45 56 23]
The dimension is 1


# Arithmatic operation in numpy arrays

# Addition

In [39]:
x = np.array([1,2,3,4,5])
y =  x+3
print(y)

[4 5 6 7 8]


# Substraction

In [40]:
x = np.array([20,40,60])
y = np.array([10,20,30])
z = x-y
print(z)

[10 20 30]


# Multipliction

In [41]:
x = np.array([20,40,60])
y = x*5
print(y)

[100 200 300]


# Division

In [42]:
x = np.array([20,40,60])
y = x/5
print(y)

[ 4.  8. 12.]


In [43]:
x = np.array([20,40,60])
y = np.array([30,20,50])

m = np.divide(x,y)
print(m)

[0.66666667 2.         1.2       ]


# Modulus

In [44]:
x = np.array([20,40,60])
y = x%5

print(y)

[0 0 0]


In [45]:
x = np.array([20,40,60])
y = x%3

print(y)

[2 1 0]


In [46]:
x = np.array([20,40,60])
m = np.array([5,10,30])

y = np.mod(x,m)
print(y)

[0 0 0]


# Arithmatic operation in 2-D array

### Addition

In [49]:
n1 = np.array([[2,4,6,8],[3,6,9,12]])
n2 = np.array([[4,8,16,20],[3,6,9,18]])

x = n1+n2
print(x)


[[ 6 12 22 28]
 [ 6 12 18 30]]


### Substraction

In [50]:
n1 = np.array([[2,4,6,8],[3,6,9,12]])
n2 = np.array([[4,8,16,20],[3,6,9,18]])

x = n1-n2
print(x)


[[ -2  -4 -10 -12]
 [  0   0   0  -6]]


### Multiplication

In [51]:
n1 = np.array([[2,4,6,8],[3,6,9,12]])
n2 = np.array([[4,8,16,20],[3,6,9,18]])

x = n1*n2
print(x)


[[  8  32  96 160]
 [  9  36  81 216]]


### Division

In [52]:
n1 = np.array([[2,4,6,8],[3,6,9,12]])
n2 = np.array([[4,8,16,20],[3,6,9,18]])

x = n1/n2
print(x)


[[0.5        0.5        0.375      0.4       ]
 [1.         1.         1.         0.66666667]]


# Arithmatic operation in 3-D array

### Addition

In [53]:
n1 = np.array([[[2,4,6,8],[3,6,9,12]]])
n2 = np.array([[[4,8,16,20],[3,6,9,18]]])

x = n1+n2
print(x)
print(x.ndim)

[[[ 6 12 22 28]
  [ 6 12 18 30]]]
3


### Substraction

In [54]:
n1 = np.array([[[2,4,6,8],[3,6,9,12]]])
n2 = np.array([[[4,8,16,20],[3,6,9,18]]])

x = n1-n2
print(x)
print(x.ndim)

[[[ -2  -4 -10 -12]
  [  0   0   0  -6]]]
3


### Multiplication

In [55]:
n1 = np.array([[[2,4,6,8],[3,6,9,12]]])
n2 = np.array([[[4,8,16,20],[3,6,9,18]]])

x = n1*n2
print(x)
print(x.ndim)

[[[  8  32  96 160]
  [  9  36  81 216]]]
3


### Division

In [56]:
n1 = np.array([[[2,4,6,8],[3,6,9,12]]])
n2 = np.array([[[4,8,16,20],[3,6,9,18]]])

x = n1/n2
print(x)
print(x.ndim)

[[[0.5        0.5        0.375      0.4       ]
  [1.         1.         1.         0.66666667]]]
3


# Unique Function in Array

In [57]:
k = np.array([12,56,23,45,78,89,87,54,21,32,56,65])
print(k)

x = np.unique(k)
print(x)             # it will print which is unique element in array

[12 56 23 45 78 89 87 54 21 32 56 65]
[12 21 23 32 45 54 56 65 78 87 89]


In [58]:
k = np.array([12,56,23,45,78,89,87,54,21,32,56,65])
print(k)
x = np.unique(k,return_index = True)

print(x)             # it will print which is unique element in array

[12 56 23 45 78 89 87 54 21 32 56 65]
(array([12, 21, 23, 32, 45, 54, 56, 65, 78, 87, 89]), array([ 0,  8,  2,  9,  3,  7,  1, 11,  4,  6,  5], dtype=int64))


# Delete

In [62]:
a = np.array([12,13,14,15])
print(a)
print()

d = np.delete(a, [1])
print(d)

[12 13 14 15]

[12 14 15]


In [63]:
a = np.array([12,13,14,15])
print(a)
print()

d = np.delete(a, [0])
print(d)

[12 13 14 15]

[13 14 15]


In [65]:
a = np.array([[12,13,14,15],[16,17,18,19],[4,5,6,9]])
print(a)
print()

d = np.delete(a,1,axis=0)
print(d)

[[12 13 14 15]
 [16 17 18 19]
 [ 4  5  6  9]]

[[12 13 14 15]
 [ 4  5  6  9]]
