# Numpy Library

In [1]:
import numpy as np

In [4]:
print(np.__version__)     # double underscore

1.24.3


### Create a NumPy ndarray object

NumPy is used to work with arrays. 

The array object in numpy is called ndarray.

we can create a numpy ndarray object by using the array() function.

In [5]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])  #passing list
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass alist, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

### Use a tuple to create a NumPy array:

In [9]:
import numpy as np

In [10]:
arr = np.array((1,2,3,4,5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimension in arrays

0-D arrays or Scalars, are the elements in array. Each value in an array is a 0-D array.

### Create a 0-D array with value 20

In [13]:
arr = np.array(42)

print(arr)
print(arr.ndim)

42
0


### 1-D array

In [12]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


### 2-D array

In [15]:
arr = np.array([[1,2,3,4,5],[55,66,77,88,99]])

print(arr)

[[ 1  2  3  4  5]
 [55 66 77 88 99]]


In [17]:
z = np.array([[1,3,5,7,9],[2,4,6,8,10]])
print(z)
print(type(z))
print(z.ndim)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
<class 'numpy.ndarray'>
2


In [21]:
q = ([[2.2,3.5,6.5,.5,8.5],[4.5,6.2,3.9,5.1,3.5]])
print(q)
print(type(q))


[[2.2, 3.5, 6.5, 0.5, 8.5], [4.5, 6.2, 3.9, 5.1, 3.5]]
<class 'list'>


# 3-D Array

an array that has 2-D array(matrices) as its elements is called 3-D array.

In [23]:
z = np.array([[[1,2,3],[2,4,6]],[[4,5,6],[7,8,9]]])

print(z)
print(type(z))
print(z.ndim)

[[[1 2 3]
  [2 4 6]]

 [[4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
3


# Check mumbers of dimensions ?

In [25]:
a = np.array(123456789)
b = np.array([1,2,3,4,5])
c = np.array([[1,3,5],[2,4,6]])
d = np.array([[[1,3,5,7,9],[2,4,6,8,10]],[[5,4,3,2,1],[10,9,8,7,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimension arrays

an array can have any numbers of dimensions.

When the array is created, you can define the number of dimensions by using the ndim argument

# Create an array with 5 Dimensions and verify that it has 5 dimensions:

In [31]:
import numpy as np

In [33]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print("Number of dimensions :", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


### NumPy Array Indexing

Array indexing is the same as accessing an array element.

you can access an array element by referring to its index number.

The indexes in numpy arrays starts with 0, meaning that the first element has index 0, and the second has index 1 etc.

# Get the first element from the following array:

In [35]:
arr = np.array([12,22,33,44,55])

print(arr[0])
print(arr[1])
print(arr[2])

12
22
33


## Access 3rd, 6th, and 8th elements from the following array and add them.

In [37]:
m = np.array([45,32,56,98,78,25,5.2,6.5])

print('3rd elemed', m[2])
print('6th elemed', m[5])
print('8th elemed', m[7])


print("sum of all elemens", m[2]+m[5]+m[7])

3rd elemed 56.0
6th elemed 25.0
8th elemed 6.5
sum of all elemens 87.5


# Access 2-D arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the lement

Think of 2-D arrays likea table with rows and column, where the dimension represents the row and the index represents the column

In [38]:
arr = np.array([[10,20,30,40,50],[50,60,70,80,90]])

print("2nd element from 1st row:", arr[0,1])

2nd element from 1st row: 20


In [39]:
arr = np.array([[10,20,30,40,50],[50,60,70,80,90]])
print("4th element from 1st row:", arr[0,3])

4th element from 1st row: 40


Add the 1st element of row 1 and last element

In [40]:
arr = np.array([[10,20,30,40,50],[50,60,70,80,90]])

print("first element of 1st row:", arr[0,0])
print("first element of 2nd row:", arr[1,4])
print("sum is:", arr[0,0]+arr[1,4])


first element of 1st row: 10
first element of 2nd row: 90
sum is: 100


# Acces 3-D Array

To access element from 3-D arrays we can use the comma separated integers representing the 
dimension and the index of the element

# Access the 3rd element of the 2nd array of the first array:

In [45]:
arr =np.array([[[1,2,3],[4,5,6]],[[44,55,88],[35,56,73]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[44 55 88]
  [35 56 73]]]


In [46]:
#3rd element of the 2nd array of the first array

arr =np.array([[[1,2,3],[4,5,6]],[[44,55,88],[35,56,73]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[44 55 88]
  [35 56 73]]]
6


In [48]:
# 1st element of the 1st array of the 2nd array
arr =np.array([[[1,2,3],[4,5,6]],[[44,55,88],[35,56,73]]])
print(arr)
print(arr[1,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[44 55 88]
  [35 56 73]]]
56


In [49]:
arr =np.array([[[1,2,3],[4,5,6]],[[44,55,88],[35,56,73]]])
print(arr)
print(arr[1,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[44 55 88]
  [35 56 73]]]
88


In [51]:
arr =np.array([[[1,2,3],[4,5,6]],[[44,55,88],[35,56,73]]])
print(arr)
print(arr[0,0,2])
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[44 55 88]
  [35 56 73]]]
3
6


# Negative indexing

### negetive indexing is used to access an array from the end.

In [52]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Last element from 2nd dim:", arr[1, -1])

Last element from 2nd dim: 10


# Numpy array slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this[start:end].


We can also define the step, like this: [start:end:step].

# Slicing elements from index 1 to index 5 from the fllowing array

In [54]:
import numpy as np

In [55]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:5])
print(arr[:4])
print(arr[0:3])

print(arr[1:5:2])

[2 3 4 5]
[1 2 3 4]
[1 2 3]
[2 4]


# Slicing 2d array

In [57]:
a = np.array([[10,20,30,40,50],[100,200,300,400,500]])

print(a[1,1:4])
print(a[0,0:3])

[200 300 400]
[10 20 30]


# From both elemens, return index 2

In [58]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


Slice index 1 to index 4 (not included), this will return 2_d array

In [59]:
arr = np.array([[1,2,3,4,5,6],[5,4,6,7,8,9]])

print(arr[0:2, 1:4])

[[2 3 4]
 [4 6 7]]
